### PR TITLE
Upgrade dependencies to latest semver-compatible versions

### PR DESCRIPTION
**Pull request by maxkfranz**
This removes most vulnerability warnings.

### CODE REVIEW

**Comment by maxkfranz** [comment]
@mikekucera @chrtannus : Could you confirm that your components are not negatively affected by this upgrade?  I tested briefly, and things looked fine to me.

**Comment by chrtannus** [comment]
No problem! Working just fine.

**Comment by maxkfranz** [comment]
Did you do an `npm install` after checking out the branch?

**Comment by chrtannus** [comment]
Yes, I made sure to run `npm install `again.

**Comment by maxkfranz** [comment]
OK, thanks. I’ve forgotten to ‘npm install’ before, so just wanted to double check

**Pull request merged**
