### PR TITLE
Feature/add ndex network test menu

### PR DESCRIPTION
**Pull request by d2fong**
**General information**
- adds a new tab in the ndex import wizard when the app is running in debug mode
- provides a list of networks the user can click through to quickly import networks from a curated collection
- 

**Checklist**

Author:

- [x] One or more reviewers have been assigned.
- [x] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.
- [x] The associated GitHub issues are included (above).
- [x] Notes have been included (below).

Reviewers:

- [x] All automated checks are passing (green check next to latest commit).
- [x] At least one reviewer has signed off on the pull request.  Reviewers have two business days to review the pull request, after which the author may merge in the pull request unilaterally.

**Notes**
Image of the network set tab.  Clicking the test network opens a new tab in the browser for convenience.

Screen Shot 2022-02-28 at 9 22 52 AM

### CODE REVIEW

**Comment by maxkfranz** [comment]
Nice.  

Looks like there's a linter issue.  Semicolons are important, because missing semicolons can make the parser misinterpret certain types of lines in JS.  [You can set VSCode to automatically fix a lot of linter issues](https://www.digitalocean.com/community/tutorials/workflow-auto-eslinting) whenever you save a file; I think the repo is set up for that by default.  Could there be something that's stopping [the settings file in the repo](https://github.com/cytoscape/cytoscape-explore/blob/dev/.vscode/settings.json) from taking effect in the editor?

**Comment by d2fong** [comment]
Ok fixed the lint issues.  I'll configure the editor to auto fix these errors in the future.

**Comment by maxkfranz** [comment]
@d2fong, does this branch pass all the tests locally for you?  It's red here.

I suspect the errors aren't related to your PR.  In any case, let's hold off merging your PR until we can get things green.  Apparently, the dev instance hasn't updated itself since the 23rd because of the errors.

It's really important that everything is green for reviews to work properly and for CI instances to run.  It looks like there may be a couple of obvious problems, but there may be more to it.  I'll look into the root causes and post updates here.

**Comment by d2fong** [comment]
It seems that the tests related to history are failing when I run them.

```
  1) History (Snapshots)
       creates and lists snapshots:
     FetchError: invalid json response body at http://localhost:3000/api/history/snapshot/history_test reason: Unexpected token < in JSON at position 0
      at /Users/dylan/src/idekerlab/cytoscape-explore/node_modules/node-fetch/lib/index.js:273:32
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.<anonymous> (test/history-test.js:44:24)

  2) History (Snapshots)
       deletes snapshots:
     FetchError: invalid json response body at http://localhost:3000/api/history/snapshot/history_test reason: Unexpected token < in JSON at position 0
      at /Users/dylan/src/idekerlab/cytoscape-explore/node_modules/node-fetch/lib/index.js:273:32
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.<anonymous> (test/history-test.js:75:24)

  3) History (Snapshots)
       restores snapshots:
     FetchError: invalid json response body at http://localhost:3000/api/history/snapshot/history_test reason: Unexpected token < in JSON at position 0
      at /Users/dylan/src/idekerlab/cytoscape-explore/node_modules/node-fetch/lib/index.js:273:32
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.<anonymous> (test/history-test.js:99:24)

  4) History (Snapshots)
       creates thumbnails:
     FetchError: invalid json response body at http://localhost:3000/api/history/snapshot/history_test reason: Unexpected token < in JSON at position 0
      at /Users/dylan/src/idekerlab/cytoscape-explore/node_modules/node-fetch/lib/index.js:273:32
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.<anonymous> (test/history-test.js:165:24)

  5) CytoscapeSyncher
       on two clients through proxy server
         "before each" hook for "client2 loads existing doc":
     FetchError: invalid json response body at http://localhost:3000/api/document reason: Unexpected token < in JSON at position 0
      at /Users/dylan/src/idekerlab/cytoscape-explore/node_modules/node-fetch/lib/index.js:273:32
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.<anonymous> (test/syncher-test.js:197:23)

  6) CytoscapeSyncher
       on two clients through proxy server
         "after each" hook for "client2 loads existing doc":
     Error: database is destroyed
      at PouchDB.<anonymous> (node_modules/pouchdb/lib/index.js:273:29)
      at PouchDB.<anonymous> (node_modules/argsarray/index.js:14:18)
      at /Users/dylan/src/idekerlab/cytoscape-explore/node_modules/pouchdb/lib/index.js:227:21
      at new Promise (<anonymous>)
      at PouchDB.<anonymous> (node_modules/pouchdb/lib/index.js:214:19)
      at PouchDB.destroy (node_modules/argsarray/index.js:16:18)
      at CytoscapeSyncher.delete (src/model/cytoscape-syncher.js:243:24)
      at Context.<anonymous> (test/syncher-test.js:210:27)
      at processImmediate (node:internal/timers:464:21)
```

**Comment by maxkfranz** [comment]
That's a good observation.  It looks like there are a few other things going on as well.  For more details see #141

**Comment by d2fong** [comment]
I get an issue related to 'react-transition-group' when I try to build the app.  It looks related to the history feature.  Updating package.json to include the missing dependency.

**Comment by maxkfranz** [comment]
> I get an issue related to 'react-transition-group' when I try to build the app. It looks related to the history feature. Updating package.json to include the missing dependency.

On `dev` on `node v14.18.3 (npm v6.14.15)`, this passes:

```
npm i
npm run build
npm test
```

It looks like it's a transitive dependency, so it should mostly work before -- though it ought to be explicit like you suggested.  Good catch

```
cytoscape-explore % npm ls react-transition-group
cytoscape-explore@0.0.0
└─┬ @material-ui/core@4.12.3
  └── react-transition-group@4.4.2
```

**Review by maxkfranz — APPROVED** [review]

**Comment by d2fong** [comment]
Oh, ok.  But according to this line, Mike is importing it directly here: https://github.com/cytoscape/cytoscape-explore/blob/ed8640ca5eb243e76a4b9499e0d52fd418ad576b/src/client/components/network-editor/history-panel.js#L6

**Comment by maxkfranz** [comment]
That's right.  An import works with direct dependencies in package.json, and they also work with transitive dependencies.  However, things we import should be listed as direct dependencies as you pointed out.  

Transitive dependencies could be deleted by a library author, for example.

**Pull request merged**
