### PR TITLE
Feature/shape icons

### PR DESCRIPTION
**Pull request by chrtannus**
@mikekucera : Can you please take a look at this and see if I broke something?
And feel free to clean up (e.g. remove the css that used to draw the shapes) or refactor the code as necessary.
I'm also getting this error:
```
vizmapper.js:42 Uncaught Error: A style value must be generated from the 'styleFactory'.  This value object is invalid, as it's missing the 'value' field.
    at assertValueIsSupported (vizmapper.js:42)
    at VizMapper.set (vizmapper.js:102)
    at NetworkEditorController.setString (controller.js:334)
    at Object.onValueSet (style-panel.js:129)
    at StylePicker.onStyleChanged (style-picker.js:86)
    at StylePicker.handleStyleChange (style-picker.js:126)
    at onSelect (style-picker.js:160)
    at onChange (shapes.js:103)
    at handleExclusiveChange (ToggleButtonGroup.js:92)
    at handleChange (ToggleButton.js:100)
```

### CODE REVIEW

**Comment by mikekucera** [comment]
@chrtannus Looks awesome!
I removed the shapes.css file altogether, its not needed anymore.

**Comment by mikekucera** [comment]
I'm not getting that error. What are the steps to reproduce it?

**Comment by maxkfranz** [comment]
@chrtannus, was the error on an old document?  It could be that the format was changed slightly.  Could you try on a fresh document (i.e. clear couchdb)?

**Comment by chrtannus** [comment]
@maxkfranz I think so. I just deleted all documents from the DB and the error is gone.

**Comment by maxkfranz** [comment]
OK, if there's no bug then let's just merge this in

**Pull request merged**
